# Copyright 2025 Accenture

name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  bazel-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: bazelbuild/setup-bazelisk@v3

      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install -y clang

      - uses: actions/cache@v4
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build all workspace targets
        run: bazel build //...

      - name: Run all workspace tests
        run: bazel test //...

      - name: Lint rust code (with clippy)
        run: bazel build --config=lint-rust //...

  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.83.0
          components: clippy, rustfmt

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install -y clang

      - run: cargo clippy --all-features

      - run: cargo fmt --check

      - run: cargo build

  cargo-miri:
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: "-Zmiri-disable-isolation"
    steps:
      - uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2024-12-17
          components: miri, rust-src

      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install -y clang

      - run: cargo +nightly-2024-12-17 miri test

